CREATE TABLE [dbo].[tenant]
(
  [id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  [key] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
  [name] NVARCHAR(512) NOT NULL,
  [created_at] DATETIME NOT NULL,
  [updated_at] DATETIME NOT NULL,
  [is_enabled] BIT NOT NULL DEFAULT 1,
)
